# Generated by Django 3.1.1 on 2020-09-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search_query',
            new_name='query',
        ),
    ]
