# Generated by Django 3.1.2 on 2020-10-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('search_app', '0002_auto_20200917_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='query',
        ),
        migrations.AddField(
            model_name='document',
            name='snippet',
            field=models.CharField(default='Sample text', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='text',
            field=models.TextField(default='Sample text'),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(default='Sample text'),
        ),
    ]
