# Generated by Django 3.1.2 on 2020-10-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_auto_20201002_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='snippet',
        ),
    ]
